;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-advanced-reader.ss" "lang")((modname exercise89) (read-case-sensitive #t) (teachpacks ()) (htdp-settings #(#t constructor repeating-decimal #t #t none #f ())))
(define (tank-move w)
  (make-tank (+ (tank-loc w) (tank-vel w))
             (tank-vel w)))
(define ufo-move-speed 3)
(define missile-move-speed 5)
(define ufo-random-range 2)
(define (ufo-move w)
  (make-posn (+ (posn-x w) (- (random (+ (* 2 ufo-random-range) 1)) ufo-random-range))
             (+ (posn-y w) ufo-move-speed)))
(define (missile-move w)
  (make-posn (posn-x w) 
             (- (posn-y w) missile-move-speed)))
(define (si-move w) 
  (if (aim? w)
      (make-aim (ufo-move (aim-ufo w))
                (tank-move (aim-tank w)))
      (make-fired (ufo-move (fired-ufo w))
                  (tank-move (fired-tank w))
                  (missile-move (fired-missile w)))))
(define width 200)
(define height 200)
(define-struct aim (ufo tank))
(define-struct fired (ufo tank missile))
(define-struct tank (loc vel))