;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-advanced-reader.ss" "lang")((modname exercise88) (read-case-sensitive #t) (teachpacks ()) (htdp-settings #(#t constructor repeating-decimal #t #t none #f ())))
(define R 10)
(define (in-reach? x)
  (< (if (posn? (abs x))
         (sqrt(+(sqr(posn-x x))
                (sqr(posn-y x))))
         x)
     R))
(define (si-game-over? si)
  (if (aim? si)
      (in-reach? (- (posn-y (aim-ufo si)) height))
      (and (in-reach? (- (posn-y (fired-ufo si)) height))
           (in-reach? (make-posn (- (posn-x (fired-ufo si)) (posn-x (fired-missile si)))
                                 (- (posn-y (fired-ufo si)) (posn-y (fired-missile si))))))))
(define width 200)
(define height 200)
(define-struct aim (ufo tank))
(define-struct fired (ufo tank missile))
(define-struct tank (loc vel))